version: 2
updates:
- package-ecosystem: docker
  directory: "/hexionbunker"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/hexionbunker/rootfs/opt/hexionbunker"
  schedule:
    interval: daily
